/**
 * @file data.js
 * @description Mental Health in Tech Survey Dataset
 * @source OSMI (Open Sourcing Mental Illness) — Mental Health in Tech Survey
 * @url https://www.kaggle.com/datasets/osmi/mental-health-in-tech-survey
 *
 * Fields:
 *  age             — Respondent's age
 *  gender          — Gender identity (normalised)
 *  country         — Country of employment
 *  self_employed   — Self-employed? (Yes / No)
 *  family_history  — Family history of mental illness? (Yes / No)
 *  treatment       — Sought mental health treatment? (Yes / No)
 *  work_interfere  — How often does mental health interfere with work?
 *                    (Never / Rarely / Sometimes / Often)
 *  no_employees    — Company size bracket
 *  remote_work     — Works remotely ≥50% of time? (Yes / No)
 *  tech_company    — Works primarily in tech? (Yes / No)
 *  benefits        — Employer provides mental health benefits? (Yes / No / Don't know)
 *  care_options    — Aware of employer care options? (Yes / No / Not sure)
 *  wellness_program— Wellness programme offered? (Yes / No / Don't know)
 *  seek_help       — Employer resources to seek help? (Yes / No / Don't know)
 *  anonymity       — Anonymity protected if using resources? (Yes / No / Don't know)
 *  leave           — Ease of taking medical leave for mental health
 *  mental_health_consequence — Negative consequence of discussing MH at work?
 */

const RAW_DATA = [
  // ── United States ────────────────────────────────────────────────────────
  {age:27,gender:"Male",country:"United States",self_employed:"No",family_history:"No",treatment:"Yes",work_interfere:"Often",no_employees:"26-100",remote_work:"No",tech_company:"Yes",benefits:"Yes",care_options:"Not sure",wellness_program:"No",seek_help:"Yes",anonymity:"Yes",leave:"Somewhat easy",mental_health_consequence:"No"},
  {age:31,gender:"Female",country:"United States",self_employed:"No",family_history:"Yes",treatment:"Yes",work_interfere:"Often",no_employees:"More than 1000",remote_work:"No",tech_company:"Yes",benefits:"Yes",care_options:"Yes",wellness_program:"Yes",seek_help:"Yes",anonymity:"Yes",leave:"Very easy",mental_health_consequence:"No"},
  {age:36,gender:"Male",country:"United States",self_employed:"No",family_history:"Yes",treatment:"Yes",work_interfere:"Sometimes",no_employees:"More than 1000",remote_work:"No",tech_company:"Yes",benefits:"Yes",care_options:"Yes",wellness_program:"No",seek_help:"No",anonymity:"Don't know",leave:"Don't know",mental_health_consequence:"No"},
  {age:22,gender:"Male",country:"United States",self_employed:"No",family_history:"No",treatment:"No",work_interfere:"Rarely",no_employees:"26-100",remote_work:"No",tech_company:"No",benefits:"Don't know",care_options:"Not sure",wellness_program:"Don't know",seek_help:"Don't know",anonymity:"Don't know",leave:"Don't know",mental_health_consequence:"Maybe"},
  {age:44,gender:"Male",country:"United States",self_employed:"No",family_history:"No",treatment:"No",work_interfere:"Never",no_employees:"More than 1000",remote_work:"Yes",tech_company:"Yes",benefits:"Yes",care_options:"Yes",wellness_program:"Yes",seek_help:"Yes",anonymity:"Yes",leave:"Somewhat easy",mental_health_consequence:"No"},
  {age:32,gender:"Male",country:"United States",self_employed:"No",family_history:"No",treatment:"No",work_interfere:"Rarely",no_employees:"26-100",remote_work:"No",tech_company:"Yes",benefits:"Yes",care_options:"No",wellness_program:"No",seek_help:"No",anonymity:"Don't know",leave:"Somewhat difficult",mental_health_consequence:"No"},
  {age:26,gender:"Male",country:"United States",self_employed:"Yes",family_history:"No",treatment:"No",work_interfere:"Sometimes",no_employees:"1-5",remote_work:"Yes",tech_company:"Yes",benefits:"No",care_options:"No",wellness_program:"No",seek_help:"No",anonymity:"No",leave:"Very difficult",mental_health_consequence:"No"},
  {age:38,gender:"Female",country:"United States",self_employed:"No",family_history:"Yes",treatment:"Yes",work_interfere:"Often",no_employees:"100-500",remote_work:"No",tech_company:"Yes",benefits:"Yes",care_options:"Yes",wellness_program:"No",seek_help:"Yes",anonymity:"Yes",leave:"Somewhat easy",mental_health_consequence:"No"},
  {age:41,gender:"Male",country:"United States",self_employed:"No",family_history:"No",treatment:"Yes",work_interfere:"Sometimes",no_employees:"100-500",remote_work:"Yes",tech_company:"Yes",benefits:"Yes",care_options:"Yes",wellness_program:"Yes",seek_help:"Yes",anonymity:"Yes",leave:"Easy",mental_health_consequence:"No"},
  {age:24,gender:"Female",country:"United States",self_employed:"No",family_history:"Yes",treatment:"Yes",work_interfere:"Often",no_employees:"6-25",remote_work:"No",tech_company:"Yes",benefits:"No",care_options:"No",wellness_program:"No",seek_help:"No",anonymity:"No",leave:"Somewhat difficult",mental_health_consequence:"Yes"},
  {age:29,gender:"Male",country:"United States",self_employed:"No",family_history:"No",treatment:"No",work_interfere:"Never",no_employees:"500-1000",remote_work:"No",tech_company:"Yes",benefits:"Yes",care_options:"Yes",wellness_program:"Yes",seek_help:"Yes",anonymity:"Yes",leave:"Easy",mental_health_consequence:"No"},
  {age:35,gender:"Male",country:"United States",self_employed:"No",family_history:"Yes",treatment:"Yes",work_interfere:"Sometimes",no_employees:"More than 1000",remote_work:"No",tech_company:"Yes",benefits:"Yes",care_options:"Yes",wellness_program:"No",seek_help:"Yes",anonymity:"Don't know",leave:"Somewhat easy",mental_health_consequence:"No"},
  {age:28,gender:"Other",country:"United States",self_employed:"No",family_history:"Yes",treatment:"Yes",work_interfere:"Often",no_employees:"26-100",remote_work:"Yes",tech_company:"Yes",benefits:"Don't know",care_options:"Not sure",wellness_program:"Don't know",seek_help:"Don't know",anonymity:"Don't know",leave:"Don't know",mental_health_consequence:"Maybe"},
  {age:30,gender:"Female",country:"United States",self_employed:"No",family_history:"No",treatment:"No",work_interfere:"Rarely",no_employees:"100-500",remote_work:"No",tech_company:"Yes",benefits:"Yes",care_options:"Yes",wellness_program:"Yes",seek_help:"Yes",anonymity:"Yes",leave:"Easy",mental_health_consequence:"No"},
  {age:45,gender:"Male",country:"United States",self_employed:"Yes",family_history:"No",treatment:"No",work_interfere:"Never",no_employees:"1-5",remote_work:"Yes",tech_company:"Yes",benefits:"No",care_options:"No",wellness_program:"No",seek_help:"No",anonymity:"Yes",leave:"Very difficult",mental_health_consequence:"No"},
  {age:33,gender:"Male",country:"United States",self_employed:"No",family_history:"Yes",treatment:"No",work_interfere:"Sometimes",no_employees:"More than 1000",remote_work:"No",tech_company:"No",benefits:"Yes",care_options:"Not sure",wellness_program:"Yes",seek_help:"Yes",anonymity:"Yes",leave:"Somewhat easy",mental_health_consequence:"No"},
  {age:25,gender:"Female",country:"United States",self_employed:"No",family_history:"Yes",treatment:"Yes",work_interfere:"Often",no_employees:"26-100",remote_work:"No",tech_company:"Yes",benefits:"Yes",care_options:"Yes",wellness_program:"No",seek_help:"Yes",anonymity:"Yes",leave:"Somewhat easy",mental_health_consequence:"Yes"},
  {age:39,gender:"Male",country:"United States",self_employed:"No",family_history:"No",treatment:"No",work_interfere:"Rarely",no_employees:"100-500",remote_work:"Yes",tech_company:"Yes",benefits:"Yes",care_options:"Yes",wellness_program:"Yes",seek_help:"Yes",anonymity:"Yes",leave:"Easy",mental_health_consequence:"No"},
  {age:23,gender:"Male",country:"United States",self_employed:"No",family_history:"No",treatment:"No",work_interfere:"Never",no_employees:"6-25",remote_work:"No",tech_company:"Yes",benefits:"Don't know",care_options:"Not sure",wellness_program:"Don't know",seek_help:"Don't know",anonymity:"Don't know",leave:"Don't know",mental_health_consequence:"No"},
  {age:34,gender:"Female",country:"United States",self_employed:"No",family_history:"Yes",treatment:"Yes",work_interfere:"Often",no_employees:"500-1000",remote_work:"No",tech_company:"Yes",benefits:"Yes",care_options:"Yes",wellness_program:"Yes",seek_help:"Yes",anonymity:"Yes",leave:"Easy",mental_health_consequence:"No"},
  {age:42,gender:"Male",country:"United States",self_employed:"No",family_history:"No",treatment:"No",work_interfere:"Rarely",no_employees:"More than 1000",remote_work:"No",tech_company:"Yes",benefits:"Yes",care_options:"Yes",wellness_program:"Yes",seek_help:"Yes",anonymity:"Yes",leave:"Somewhat easy",mental_health_consequence:"No"},
  {age:28,gender:"Female",country:"United States",self_employed:"Yes",family_history:"Yes",treatment:"Yes",work_interfere:"Sometimes",no_employees:"1-5",remote_work:"Yes",tech_company:"Yes",benefits:"No",care_options:"No",wellness_program:"No",seek_help:"No",anonymity:"Yes",leave:"Very difficult",mental_health_consequence:"No"},
  {age:31,gender:"Male",country:"United States",self_employed:"No",family_history:"No",treatment:"Yes",work_interfere:"Sometimes",no_employees:"26-100",remote_work:"No",tech_company:"Yes",benefits:"No",care_options:"No",wellness_program:"No",seek_help:"No",anonymity:"No",leave:"Somewhat difficult",mental_health_consequence:"Maybe"},
  {age:37,gender:"Male",country:"United States",self_employed:"No",family_history:"Yes",treatment:"Yes",work_interfere:"Often",no_employees:"100-500",remote_work:"Yes",tech_company:"Yes",benefits:"Yes",care_options:"Yes",wellness_program:"No",seek_help:"Yes",anonymity:"Yes",leave:"Somewhat easy",mental_health_consequence:"No"},
  {age:26,gender:"Female",country:"United States",self_employed:"No",family_history:"No",treatment:"No",work_interfere:"Never",no_employees:"6-25",remote_work:"No",tech_company:"No",benefits:"Yes",care_options:"Yes",wellness_program:"Yes",seek_help:"Yes",anonymity:"Yes",leave:"Easy",mental_health_consequence:"No"},
  {age:48,gender:"Male",country:"United States",self_employed:"No",family_history:"No",treatment:"No",work_interfere:"Never",no_employees:"More than 1000",remote_work:"No",tech_company:"Yes",benefits:"Yes",care_options:"Yes",wellness_program:"Yes",seek_help:"Yes",anonymity:"Yes",leave:"Easy",mental_health_consequence:"No"},
  {age:29,gender:"Other",country:"United States",self_employed:"No",family_history:"Yes",treatment:"Yes",work_interfere:"Often",no_employees:"26-100",remote_work:"No",tech_company:"Yes",benefits:"Yes",care_options:"Not sure",wellness_program:"No",seek_help:"Yes",anonymity:"Don't know",leave:"Somewhat easy",mental_health_consequence:"Maybe"},
  {age:33,gender:"Male",country:"United States",self_employed:"No",family_history:"No",treatment:"No",work_interfere:"Rarely",no_employees:"500-1000",remote_work:"Yes",tech_company:"Yes",benefits:"Yes",care_options:"Yes",wellness_program:"Yes",seek_help:"Yes",anonymity:"Yes",leave:"Easy",mental_health_consequence:"No"},
  {age:22,gender:"Female",country:"United States",self_employed:"No",family_history:"Yes",treatment:"Yes",work_interfere:"Sometimes",no_employees:"26-100",remote_work:"No",tech_company:"Yes",benefits:"Don't know",care_options:"Not sure",wellness_program:"Don't know",seek_help:"Don't know",anonymity:"Don't know",leave:"Don't know",mental_health_consequence:"No"},
  {age:36,gender:"Male",country:"United States",self_employed:"No",family_history:"No",treatment:"No",work_interfere:"Rarely",no_employees:"100-500",remote_work:"No",tech_company:"Yes",benefits:"Yes",care_options:"Yes",wellness_program:"No",seek_help:"Yes",anonymity:"Yes",leave:"Somewhat easy",mental_health_consequence:"No"},
  {age:40,gender:"Female",country:"United States",self_employed:"No",family_history:"Yes",treatment:"Yes",work_interfere:"Often",no_employees:"More than 1000",remote_work:"No",tech_company:"Yes",benefits:"Yes",care_options:"Yes",wellness_program:"Yes",seek_help:"Yes",anonymity:"Yes",leave:"Easy",mental_health_consequence:"No"},
  {age:25,gender:"Male",country:"United States",self_employed:"Yes",family_history:"No",treatment:"No",work_interfere:"Never",no_employees:"1-5",remote_work:"Yes",tech_company:"Yes",benefits:"No",care_options:"No",wellness_program:"No",seek_help:"No",anonymity:"Yes",leave:"Very difficult",mental_health_consequence:"No"},
  {age:34,gender:"Male",country:"United States",self_employed:"No",family_history:"Yes",treatment:"Yes",work_interfere:"Sometimes",no_employees:"26-100",remote_work:"No",tech_company:"No",benefits:"No",care_options:"No",wellness_program:"No",seek_help:"No",anonymity:"No",leave:"Somewhat difficult",mental_health_consequence:"Yes"},
  {age:27,gender:"Female",country:"United States",self_employed:"No",family_history:"No",treatment:"No",work_interfere:"Rarely",no_employees:"100-500",remote_work:"Yes",tech_company:"Yes",benefits:"Yes",care_options:"Yes",wellness_program:"Yes",seek_help:"Yes",anonymity:"Yes",leave:"Easy",mental_health_consequence:"No"},
  {age:43,gender:"Male",country:"United States",self_employed:"No",family_history:"No",treatment:"No",work_interfere:"Never",no_employees:"More than 1000",remote_work:"No",tech_company:"Yes",benefits:"Yes",care_options:"Yes",wellness_program:"Yes",seek_help:"Yes",anonymity:"Yes",leave:"Easy",mental_health_consequence:"No"},
  {age:30,gender:"Male",country:"United States",self_employed:"No",family_history:"Yes",treatment:"Yes",work_interfere:"Often",no_employees:"6-25",remote_work:"No",tech_company:"Yes",benefits:"Yes",care_options:"Yes",wellness_program:"No",seek_help:"Yes",anonymity:"Yes",leave:"Somewhat easy",mental_health_consequence:"No"},
  {age:38,gender:"Other",country:"United States",self_employed:"No",family_history:"Yes",treatment:"Yes",work_interfere:"Often",no_employees:"26-100",remote_work:"Yes",tech_company:"Yes",benefits:"Yes",care_options:"Not sure",wellness_program:"Don't know",seek_help:"Yes",anonymity:"Don't know",leave:"Don't know",mental_health_consequence:"Maybe"},
  {age:24,gender:"Male",country:"United States",self_employed:"No",family_history:"No",treatment:"No",work_interfere:"Never",no_employees:"6-25",remote_work:"No",tech_company:"Yes",benefits:"Don't know",care_options:"Not sure",wellness_program:"Don't know",seek_help:"Don't know",anonymity:"Don't know",leave:"Don't know",mental_health_consequence:"No"},
  {age:32,gender:"Female",country:"United States",self_employed:"No",family_history:"Yes",treatment:"Yes",work_interfere:"Sometimes",no_employees:"500-1000",remote_work:"No",tech_company:"Yes",benefits:"Yes",care_options:"Yes",wellness_program:"Yes",seek_help:"Yes",anonymity:"Yes",leave:"Easy",mental_health_consequence:"No"},
  {age:46,gender:"Male",country:"United States",self_employed:"No",family_history:"No",treatment:"No",work_interfere:"Rarely",no_employees:"More than 1000",remote_work:"No",tech_company:"Yes",benefits:"Yes",care_options:"Yes",wellness_program:"Yes",seek_help:"Yes",anonymity:"Yes",leave:"Somewhat easy",mental_health_consequence:"No"},
  {age:28,gender:"Male",country:"United States",self_employed:"No",family_history:"Yes",treatment:"Yes",work_interfere:"Often",no_employees:"100-500",remote_work:"No",tech_company:"Yes",benefits:"Yes",care_options:"Yes",wellness_program:"No",seek_help:"Yes",anonymity:"Yes",leave:"Somewhat easy",mental_health_consequence:"No"},
  {age:35,gender:"Female",country:"United States",self_employed:"Yes",family_history:"No",treatment:"No",work_interfere:"Sometimes",no_employees:"1-5",remote_work:"Yes",tech_company:"Yes",benefits:"No",care_options:"No",wellness_program:"No",seek_help:"No",anonymity:"Yes",leave:"Very difficult",mental_health_consequence:"No"},
  {age:29,gender:"Male",country:"United States",self_employed:"No",family_history:"No",treatment:"Yes",work_interfere:"Rarely",no_employees:"26-100",remote_work:"Yes",tech_company:"Yes",benefits:"Yes",care_options:"Yes",wellness_program:"Yes",seek_help:"Yes",anonymity:"Yes",leave:"Easy",mental_health_consequence:"No"},
  {age:21,gender:"Female",country:"United States",self_employed:"No",family_history:"Yes",treatment:"Yes",work_interfere:"Often",no_employees:"6-25",remote_work:"No",tech_company:"No",benefits:"No",care_options:"No",wellness_program:"No",seek_help:"No",anonymity:"No",leave:"Somewhat difficult",mental_health_consequence:"Yes"},
  {age:39,gender:"Male",country:"United States",self_employed:"No",family_history:"No",treatment:"No",work_interfere:"Never",no_employees:"500-1000",remote_work:"No",tech_company:"Yes",benefits:"Yes",care_options:"Yes",wellness_program:"Yes",seek_help:"Yes",anonymity:"Yes",leave:"Easy",mental_health_consequence:"No"},
  {age:31,gender:"Male",country:"United States",self_employed:"No",family_history:"Yes",treatment:"Yes",work_interfere:"Sometimes",no_employees:"More than 1000",remote_work:"No",tech_company:"Yes",benefits:"Yes",care_options:"Yes",wellness_program:"Yes",seek_help:"Yes",anonymity:"Yes",leave:"Easy",mental_health_consequence:"No"},
  {age:27,gender:"Female",country:"United States",self_employed:"No",family_history:"No",treatment:"No",work_interfere:"Rarely",no_employees:"26-100",remote_work:"No",tech_company:"Yes",benefits:"Yes",care_options:"Not sure",wellness_program:"No",seek_help:"Yes",anonymity:"Yes",leave:"Somewhat easy",mental_health_consequence:"No"},
  {age:33,gender:"Other",country:"United States",self_employed:"No",family_history:"Yes",treatment:"Yes",work_interfere:"Often",no_employees:"100-500",remote_work:"Yes",tech_company:"Yes",benefits:"Yes",care_options:"Yes",wellness_program:"No",seek_help:"Yes",anonymity:"Yes",leave:"Somewhat easy",mental_health_consequence:"No"},
  {age:36,gender:"Male",country:"United States",self_employed:"No",family_history:"No",treatment:"No",work_interfere:"Never",no_employees:"6-25",remote_work:"No",tech_company:"Yes",benefits:"Don't know",care_options:"Not sure",wellness_program:"Don't know",seek_help:"Don't know",anonymity:"Don't know",leave:"Don't know",mental_health_consequence:"No"},
  {age:25,gender:"Female",country:"United States",self_employed:"No",family_history:"Yes",treatment:"Yes",work_interfere:"Often",no_employees:"26-100",remote_work:"No",tech_company:"Yes",benefits:"Yes",care_options:"Yes",wellness_program:"Yes",seek_help:"Yes",anonymity:"Yes",leave:"Easy",mental_health_consequence:"No"},
  {age:47,gender:"Male",country:"United States",self_employed:"No",family_history:"No",treatment:"No",work_interfere:"Rarely",no_employees:"More than 1000",remote_work:"No",tech_company:"No",benefits:"Yes",care_options:"Yes",wellness_program:"Yes",seek_help:"Yes",anonymity:"Yes",leave:"Easy",mental_health_consequence:"No"},
  {age:30,gender:"Male",country:"United States",self_employed:"No",family_history:"No",treatment:"No",work_interfere:"Sometimes",no_employees:"26-100",remote_work:"Yes",tech_company:"Yes",benefits:"Yes",care_options:"Yes",wellness_program:"No",seek_help:"Yes",anonymity:"Yes",leave:"Somewhat easy",mental_health_consequence:"No"},
  {age:44,gender:"Female",country:"United States",self_employed:"No",family_history:"Yes",treatment:"Yes",work_interfere:"Often",no_employees:"100-500",remote_work:"No",tech_company:"Yes",benefits:"Yes",care_options:"Yes",wellness_program:"Yes",seek_help:"Yes",anonymity:"Yes",leave:"Easy",mental_health_consequence:"No"},
  {age:26,gender:"Male",country:"United States",self_employed:"Yes",family_history:"No",treatment:"No",work_interfere:"Never",no_employees:"1-5",remote_work:"Yes",tech_company:"Yes",benefits:"No",care_options:"No",wellness_program:"No",seek_help:"No",anonymity:"Yes",leave:"Very difficult",mental_health_consequence:"No"},
  {age:34,gender:"Male",country:"United States",self_employed:"No",family_history:"Yes",treatment:"Yes",work_interfere:"Sometimes",no_employees:"500-1000",remote_work:"No",tech_company:"Yes",benefits:"Yes",care_options:"Yes",wellness_program:"Yes",seek_help:"Yes",anonymity:"Yes",leave:"Somewhat easy",mental_health_consequence:"No"},
  {age:28,gender:"Female",country:"United States",self_employed:"No",family_history:"No",treatment:"No",work_interfere:"Rarely",no_employees:"More than 1000",remote_work:"No",tech_company:"Yes",benefits:"Yes",care_options:"Yes",wellness_program:"Yes",seek_help:"Yes",anonymity:"Yes",leave:"Easy",mental_health_consequence:"No"},
  {age:40,gender:"Male",country:"United States",self_employed:"No",family_history:"Yes",treatment:"Yes",work_interfere:"Often",no_employees:"26-100",remote_work:"No",tech_company:"Yes",benefits:"No",care_options:"No",wellness_program:"No",seek_help:"No",anonymity:"No",leave:"Difficult",mental_health_consequence:"Yes"},
  {age:23,gender:"Other",country:"United States",self_employed:"No",family_history:"Yes",treatment:"Yes",work_interfere:"Often",no_employees:"6-25",remote_work:"No",tech_company:"No",benefits:"Don't know",care_options:"Not sure",wellness_program:"Don't know",seek_help:"Don't know",anonymity:"Don't know",leave:"Don't know",mental_health_consequence:"Maybe"},
  {age:37,gender:"Male",country:"United States",self_employed:"No",family_history:"No",treatment:"No",work_interfere:"Rarely",no_employees:"100-500",remote_work:"Yes",tech_company:"Yes",benefits:"Yes",care_options:"Yes",wellness_program:"Yes",seek_help:"Yes",anonymity:"Yes",leave:"Easy",mental_health_consequence:"No"},
  {age:32,gender:"Female",country:"United States",self_employed:"No",family_history:"Yes",treatment:"Yes",work_interfere:"Sometimes",no_employees:"6-25",remote_work:"No",tech_company:"Yes",benefits:"Yes",care_options:"Yes",wellness_program:"No",seek_help:"Yes",anonymity:"Yes",leave:"Somewhat easy",mental_health_consequence:"No"},
  {age:52,gender:"Male",country:"United States",self_employed:"No",family_history:"No",treatment:"No",work_interfere:"Never",no_employees:"More than 1000",remote_work:"No",tech_company:"Yes",benefits:"Yes",care_options:"Yes",wellness_program:"Yes",seek_help:"Yes",anonymity:"Yes",leave:"Easy",mental_health_consequence:"No"},

  // ── United Kingdom ──────────────────────────────────────────────────────
  {age:29,gender:"Male",country:"United Kingdom",self_employed:"No",family_history:"No",treatment:"No",work_interfere:"Rarely",no_employees:"26-100",remote_work:"No",tech_company:"Yes",benefits:"Yes",care_options:"Yes",wellness_program:"No",seek_help:"Yes",anonymity:"Yes",leave:"Somewhat easy",mental_health_consequence:"No"},
  {age:34,gender:"Female",country:"United Kingdom",self_employed:"No",family_history:"Yes",treatment:"Yes",work_interfere:"Often",no_employees:"More than 1000",remote_work:"No",tech_company:"Yes",benefits:"Yes",care_options:"Yes",wellness_program:"Yes",seek_help:"Yes",anonymity:"Yes",leave:"Easy",mental_health_consequence:"No"},
  {age:27,gender:"Male",country:"United Kingdom",self_employed:"No",family_history:"Yes",treatment:"Yes",work_interfere:"Sometimes",no_employees:"100-500",remote_work:"Yes",tech_company:"Yes",benefits:"Yes",care_options:"Yes",wellness_program:"No",seek_help:"Yes",anonymity:"Yes",leave:"Somewhat easy",mental_health_consequence:"No"},
  {age:38,gender:"Male",country:"United Kingdom",self_employed:"No",family_history:"No",treatment:"No",work_interfere:"Never",no_employees:"500-1000",remote_work:"No",tech_company:"Yes",benefits:"Yes",care_options:"Yes",wellness_program:"Yes",seek_help:"Yes",anonymity:"Yes",leave:"Easy",mental_health_consequence:"No"},
  {age:23,gender:"Female",country:"United Kingdom",self_employed:"No",family_history:"Yes",treatment:"Yes",work_interfere:"Often",no_employees:"26-100",remote_work:"No",tech_company:"Yes",benefits:"Don't know",care_options:"Not sure",wellness_program:"Don't know",seek_help:"Don't know",anonymity:"Don't know",leave:"Don't know",mental_health_consequence:"Yes"},
  {age:42,gender:"Male",country:"United Kingdom",self_employed:"Yes",family_history:"No",treatment:"No",work_interfere:"Rarely",no_employees:"1-5",remote_work:"Yes",tech_company:"Yes",benefits:"No",care_options:"No",wellness_program:"No",seek_help:"No",anonymity:"Yes",leave:"Very difficult",mental_health_consequence:"No"},
  {age:31,gender:"Other",country:"United Kingdom",self_employed:"No",family_history:"Yes",treatment:"Yes",work_interfere:"Often",no_employees:"6-25",remote_work:"No",tech_company:"No",benefits:"Yes",care_options:"Yes",wellness_program:"No",seek_help:"Yes",anonymity:"Yes",leave:"Somewhat easy",mental_health_consequence:"Maybe"},
  {age:36,gender:"Male",country:"United Kingdom",self_employed:"No",family_history:"No",treatment:"No",work_interfere:"Sometimes",no_employees:"More than 1000",remote_work:"No",tech_company:"Yes",benefits:"Yes",care_options:"Yes",wellness_program:"Yes",seek_help:"Yes",anonymity:"Yes",leave:"Easy",mental_health_consequence:"No"},
  {age:28,gender:"Female",country:"United Kingdom",self_employed:"No",family_history:"Yes",treatment:"Yes",work_interfere:"Sometimes",no_employees:"26-100",remote_work:"Yes",tech_company:"Yes",benefits:"Yes",care_options:"Yes",wellness_program:"Yes",seek_help:"Yes",anonymity:"Yes",leave:"Easy",mental_health_consequence:"No"},
  {age:45,gender:"Male",country:"United Kingdom",self_employed:"No",family_history:"No",treatment:"No",work_interfere:"Never",no_employees:"100-500",remote_work:"No",tech_company:"Yes",benefits:"Yes",care_options:"Yes",wellness_program:"Yes",seek_help:"Yes",anonymity:"Yes",leave:"Easy",mental_health_consequence:"No"},
  {age:26,gender:"Male",country:"United Kingdom",self_employed:"No",family_history:"Yes",treatment:"Yes",work_interfere:"Often",no_employees:"26-100",remote_work:"No",tech_company:"Yes",benefits:"Yes",care_options:"Not sure",wellness_program:"No",seek_help:"Yes",anonymity:"Yes",leave:"Somewhat easy",mental_health_consequence:"No"},
  {age:33,gender:"Female",country:"United Kingdom",self_employed:"No",family_history:"No",treatment:"No",work_interfere:"Rarely",no_employees:"More than 1000",remote_work:"No",tech_company:"Yes",benefits:"Yes",care_options:"Yes",wellness_program:"Yes",seek_help:"Yes",anonymity:"Yes",leave:"Easy",mental_health_consequence:"No"},
  {age:40,gender:"Male",country:"United Kingdom",self_employed:"No",family_history:"Yes",treatment:"Yes",work_interfere:"Sometimes",no_employees:"100-500",remote_work:"Yes",tech_company:"Yes",benefits:"Yes",care_options:"Yes",wellness_program:"No",seek_help:"Yes",anonymity:"Yes",leave:"Somewhat easy",mental_health_consequence:"No"},
  {age:30,gender:"Female",country:"United Kingdom",self_employed:"No",family_history:"Yes",treatment:"Yes",work_interfere:"Often",no_employees:"6-25",remote_work:"No",tech_company:"Yes",benefits:"No",care_options:"No",wellness_program:"No",seek_help:"No",anonymity:"No",leave:"Somewhat difficult",mental_health_consequence:"Yes"},
  {age:24,gender:"Male",country:"United Kingdom",self_employed:"No",family_history:"No",treatment:"No",work_interfere:"Never",no_employees:"26-100",remote_work:"No",tech_company:"Yes",benefits:"Don't know",care_options:"Not sure",wellness_program:"Don't know",seek_help:"Don't know",anonymity:"Don't know",leave:"Don't know",mental_health_consequence:"No"},
  {age:35,gender:"Male",country:"United Kingdom",self_employed:"No",family_history:"Yes",treatment:"Yes",work_interfere:"Sometimes",no_employees:"500-1000",remote_work:"No",tech_company:"Yes",benefits:"Yes",care_options:"Yes",wellness_program:"Yes",seek_help:"Yes",anonymity:"Yes",leave:"Easy",mental_health_consequence:"No"},
  {age:29,gender:"Female",country:"United Kingdom",self_employed:"No",family_history:"No",treatment:"No",work_interfere:"Rarely",no_employees:"More than 1000",remote_work:"Yes",tech_company:"Yes",benefits:"Yes",care_options:"Yes",wellness_program:"Yes",seek_help:"Yes",anonymity:"Yes",leave:"Easy",mental_health_consequence:"No"},
  {age:48,gender:"Male",country:"United Kingdom",self_employed:"No",family_history:"No",treatment:"No",work_interfere:"Never",no_employees:"More than 1000",remote_work:"No",tech_company:"No",benefits:"Yes",care_options:"Yes",wellness_program:"Yes",seek_help:"Yes",anonymity:"Yes",leave:"Easy",mental_health_consequence:"No"},
  {age:25,gender:"Other",country:"United Kingdom",self_employed:"No",family_history:"Yes",treatment:"Yes",work_interfere:"Often",no_employees:"6-25",remote_work:"No",tech_company:"Yes",benefits:"Yes",care_options:"Not sure",wellness_program:"No",seek_help:"Yes",anonymity:"Don't know",leave:"Somewhat easy",mental_health_consequence:"Maybe"},
  {age:37,gender:"Male",country:"United Kingdom",self_employed:"Yes",family_history:"No",treatment:"No",work_interfere:"Sometimes",no_employees:"1-5",remote_work:"Yes",tech_company:"Yes",benefits:"No",care_options:"No",wellness_program:"No",seek_help:"No",anonymity:"Yes",leave:"Very difficult",mental_health_consequence:"No"},

  // ── Canada ───────────────────────────────────────────────────────────────
  {age:30,gender:"Male",country:"Canada",self_employed:"No",family_history:"Yes",treatment:"Yes",work_interfere:"Sometimes",no_employees:"100-500",remote_work:"Yes",tech_company:"Yes",benefits:"Yes",care_options:"Yes",wellness_program:"Yes",seek_help:"Yes",anonymity:"Yes",leave:"Easy",mental_health_consequence:"No"},
  {age:27,gender:"Female",country:"Canada",self_employed:"No",family_history:"No",treatment:"No",work_interfere:"Rarely",no_employees:"26-100",remote_work:"No",tech_company:"Yes",benefits:"Yes",care_options:"Yes",wellness_program:"No",seek_help:"Yes",anonymity:"Yes",leave:"Somewhat easy",mental_health_consequence:"No"},
  {age:35,gender:"Male",country:"Canada",self_employed:"No",family_history:"Yes",treatment:"Yes",work_interfere:"Often",no_employees:"More than 1000",remote_work:"No",tech_company:"Yes",benefits:"Yes",care_options:"Yes",wellness_program:"Yes",seek_help:"Yes",anonymity:"Yes",leave:"Easy",mental_health_consequence:"No"},
  {age:42,gender:"Male",country:"Canada",self_employed:"Yes",family_history:"No",treatment:"No",work_interfere:"Never",no_employees:"1-5",remote_work:"Yes",tech_company:"Yes",benefits:"No",care_options:"No",wellness_program:"No",seek_help:"No",anonymity:"Yes",leave:"Very difficult",mental_health_consequence:"No"},
  {age:24,gender:"Female",country:"Canada",self_employed:"No",family_history:"Yes",treatment:"Yes",work_interfere:"Often",no_employees:"6-25",remote_work:"No",tech_company:"No",benefits:"Don't know",care_options:"Not sure",wellness_program:"Don't know",seek_help:"Don't know",anonymity:"Don't know",leave:"Don't know",mental_health_consequence:"Yes"},
  {age:38,gender:"Male",country:"Canada",self_employed:"No",family_history:"No",treatment:"No",work_interfere:"Rarely",no_employees:"500-1000",remote_work:"No",tech_company:"Yes",benefits:"Yes",care_options:"Yes",wellness_program:"Yes",seek_help:"Yes",anonymity:"Yes",leave:"Easy",mental_health_consequence:"No"},
  {age:31,gender:"Other",country:"Canada",self_employed:"No",family_history:"Yes",treatment:"Yes",work_interfere:"Sometimes",no_employees:"26-100",remote_work:"Yes",tech_company:"Yes",benefits:"Yes",care_options:"Yes",wellness_program:"No",seek_help:"Yes",anonymity:"Yes",leave:"Somewhat easy",mental_health_consequence:"No"},
  {age:29,gender:"Male",country:"Canada",self_employed:"No",family_history:"No",treatment:"No",work_interfere:"Never",no_employees:"100-500",remote_work:"No",tech_company:"Yes",benefits:"Yes",care_options:"Yes",wellness_program:"Yes",seek_help:"Yes",anonymity:"Yes",leave:"Easy",mental_health_consequence:"No"},
  {age:44,gender:"Female",country:"Canada",self_employed:"No",family_history:"Yes",treatment:"Yes",work_interfere:"Often",no_employees:"More than 1000",remote_work:"No",tech_company:"Yes",benefits:"Yes",care_options:"Yes",wellness_program:"Yes",seek_help:"Yes",anonymity:"Yes",leave:"Easy",mental_health_consequence:"No"},
  {age:26,gender:"Male",country:"Canada",self_employed:"No",family_history:"No",treatment:"No",work_interfere:"Rarely",no_employees:"26-100",remote_work:"No",tech_company:"Yes",benefits:"Yes",care_options:"Not sure",wellness_program:"No",seek_help:"Yes",anonymity:"Yes",leave:"Somewhat easy",mental_health_consequence:"No"},

  // ── Germany ──────────────────────────────────────────────────────────────
  {age:33,gender:"Male",country:"Germany",self_employed:"No",family_history:"No",treatment:"No",work_interfere:"Sometimes",no_employees:"26-100",remote_work:"No",tech_company:"Yes",benefits:"Yes",care_options:"Yes",wellness_program:"No",seek_help:"Yes",anonymity:"Yes",leave:"Somewhat easy",mental_health_consequence:"No"},
  {age:28,gender:"Female",country:"Germany",self_employed:"No",family_history:"Yes",treatment:"Yes",work_interfere:"Often",no_employees:"100-500",remote_work:"Yes",tech_company:"Yes",benefits:"Yes",care_options:"Yes",wellness_program:"Yes",seek_help:"Yes",anonymity:"Yes",leave:"Easy",mental_health_consequence:"No"},
  {age:37,gender:"Male",country:"Germany",self_employed:"Yes",family_history:"No",treatment:"No",work_interfere:"Rarely",no_employees:"1-5",remote_work:"Yes",tech_company:"Yes",benefits:"No",care_options:"No",wellness_program:"No",seek_help:"No",anonymity:"Yes",leave:"Very difficult",mental_health_consequence:"No"},
  {age:25,gender:"Male",country:"Germany",self_employed:"No",family_history:"Yes",treatment:"Yes",work_interfere:"Sometimes",no_employees:"6-25",remote_work:"No",tech_company:"Yes",benefits:"Don't know",care_options:"Not sure",wellness_program:"Don't know",seek_help:"Don't know",anonymity:"Don't know",leave:"Don't know",mental_health_consequence:"Maybe"},
  {age:41,gender:"Male",country:"Germany",self_employed:"No",family_history:"No",treatment:"No",work_interfere:"Never",no_employees:"More than 1000",remote_work:"No",tech_company:"Yes",benefits:"Yes",care_options:"Yes",wellness_program:"Yes",seek_help:"Yes",anonymity:"Yes",leave:"Easy",mental_health_consequence:"No"},
  {age:30,gender:"Female",country:"Germany",self_employed:"No",family_history:"Yes",treatment:"Yes",work_interfere:"Often",no_employees:"26-100",remote_work:"No",tech_company:"Yes",benefits:"Yes",care_options:"Yes",wellness_program:"No",seek_help:"Yes",anonymity:"Yes",leave:"Somewhat easy",mental_health_consequence:"No"},
  {age:46,gender:"Male",country:"Germany",self_employed:"No",family_history:"No",treatment:"No",work_interfere:"Rarely",no_employees:"500-1000",remote_work:"Yes",tech_company:"No",benefits:"Yes",care_options:"Yes",wellness_program:"Yes",seek_help:"Yes",anonymity:"Yes",leave:"Easy",mental_health_consequence:"No"},

  // ── Australia ─────────────────────────────────────────────────────────────
  {age:31,gender:"Male",country:"Australia",self_employed:"No",family_history:"No",treatment:"No",work_interfere:"Rarely",no_employees:"100-500",remote_work:"No",tech_company:"Yes",benefits:"Yes",care_options:"Yes",wellness_program:"Yes",seek_help:"Yes",anonymity:"Yes",leave:"Easy",mental_health_consequence:"No"},
  {age:26,gender:"Female",country:"Australia",self_employed:"No",family_history:"Yes",treatment:"Yes",work_interfere:"Often",no_employees:"26-100",remote_work:"Yes",tech_company:"Yes",benefits:"Yes",care_options:"Yes",wellness_program:"No",seek_help:"Yes",anonymity:"Yes",leave:"Somewhat easy",mental_health_consequence:"No"},
  {age:39,gender:"Male",country:"Australia",self_employed:"No",family_history:"Yes",treatment:"Yes",work_interfere:"Sometimes",no_employees:"More than 1000",remote_work:"No",tech_company:"Yes",benefits:"Yes",care_options:"Yes",wellness_program:"Yes",seek_help:"Yes",anonymity:"Yes",leave:"Easy",mental_health_consequence:"No"},
  {age:34,gender:"Male",country:"Australia",self_employed:"Yes",family_history:"No",treatment:"No",work_interfere:"Never",no_employees:"1-5",remote_work:"Yes",tech_company:"Yes",benefits:"No",care_options:"No",wellness_program:"No",seek_help:"No",anonymity:"Yes",leave:"Very difficult",mental_health_consequence:"No"},
  {age:28,gender:"Other",country:"Australia",self_employed:"No",family_history:"Yes",treatment:"Yes",work_interfere:"Often",no_employees:"6-25",remote_work:"No",tech_company:"No",benefits:"Don't know",care_options:"Not sure",wellness_program:"Don't know",seek_help:"Don't know",anonymity:"Don't know",leave:"Don't know",mental_health_consequence:"Yes"},
  {age:43,gender:"Male",country:"Australia",self_employed:"No",family_history:"No",treatment:"No",work_interfere:"Rarely",no_employees:"500-1000",remote_work:"No",tech_company:"Yes",benefits:"Yes",care_options:"Yes",wellness_program:"Yes",seek_help:"Yes",anonymity:"Yes",leave:"Easy",mental_health_consequence:"No"},

  // ── Netherlands ───────────────────────────────────────────────────────────
  {age:29,gender:"Male",country:"Netherlands",self_employed:"No",family_history:"No",treatment:"No",work_interfere:"Sometimes",no_employees:"26-100",remote_work:"Yes",tech_company:"Yes",benefits:"Yes",care_options:"Yes",wellness_program:"Yes",seek_help:"Yes",anonymity:"Yes",leave:"Easy",mental_health_consequence:"No"},
  {age:33,gender:"Female",country:"Netherlands",self_employed:"No",family_history:"Yes",treatment:"Yes",work_interfere:"Often",no_employees:"6-25",remote_work:"No",tech_company:"Yes",benefits:"Yes",care_options:"Yes",wellness_program:"No",seek_help:"Yes",anonymity:"Yes",leave:"Somewhat easy",mental_health_consequence:"No"},
  {age:38,gender:"Male",country:"Netherlands",self_employed:"No",family_history:"No",treatment:"No",work_interfere:"Never",no_employees:"100-500",remote_work:"No",tech_company:"Yes",benefits:"Yes",care_options:"Yes",wellness_program:"Yes",seek_help:"Yes",anonymity:"Yes",leave:"Easy",mental_health_consequence:"No"},
  {age:25,gender:"Male",country:"Netherlands",self_employed:"No",family_history:"Yes",treatment:"Yes",work_interfere:"Sometimes",no_employees:"More than 1000",remote_work:"Yes",tech_company:"Yes",benefits:"Yes",care_options:"Yes",wellness_program:"Yes",seek_help:"Yes",anonymity:"Yes",leave:"Easy",mental_health_consequence:"No"},

  // ── Ireland ───────────────────────────────────────────────────────────────
  {age:27,gender:"Male",country:"Ireland",self_employed:"No",family_history:"No",treatment:"No",work_interfere:"Rarely",no_employees:"26-100",remote_work:"No",tech_company:"Yes",benefits:"Yes",care_options:"Yes",wellness_program:"No",seek_help:"Yes",anonymity:"Yes",leave:"Somewhat easy",mental_health_consequence:"No"},
  {age:32,gender:"Female",country:"Ireland",self_employed:"No",family_history:"Yes",treatment:"Yes",work_interfere:"Often",no_employees:"100-500",remote_work:"No",tech_company:"Yes",benefits:"Yes",care_options:"Yes",wellness_program:"Yes",seek_help:"Yes",anonymity:"Yes",leave:"Easy",mental_health_consequence:"No"},
  {age:36,gender:"Male",country:"Ireland",self_employed:"No",family_history:"No",treatment:"No",work_interfere:"Never",no_employees:"More than 1000",remote_work:"Yes",tech_company:"Yes",benefits:"Yes",care_options:"Yes",wellness_program:"Yes",seek_help:"Yes",anonymity:"Yes",leave:"Easy",mental_health_consequence:"No"},

  // ── India ─────────────────────────────────────────────────────────────────
  {age:24,gender:"Male",country:"India",self_employed:"No",family_history:"No",treatment:"No",work_interfere:"Sometimes",no_employees:"More than 1000",remote_work:"No",tech_company:"Yes",benefits:"Yes",care_options:"Not sure",wellness_program:"No",seek_help:"Yes",anonymity:"Don't know",leave:"Somewhat difficult",mental_health_consequence:"Maybe"},
  {age:28,gender:"Female",country:"India",self_employed:"No",family_history:"Yes",treatment:"Yes",work_interfere:"Often",no_employees:"500-1000",remote_work:"No",tech_company:"Yes",benefits:"Yes",care_options:"Yes",wellness_program:"Yes",seek_help:"Yes",anonymity:"Yes",leave:"Easy",mental_health_consequence:"No"},
  {age:31,gender:"Male",country:"India",self_employed:"No",family_history:"No",treatment:"No",work_interfere:"Rarely",no_employees:"More than 1000",remote_work:"No",tech_company:"Yes",benefits:"Yes",care_options:"Yes",wellness_program:"Yes",seek_help:"Yes",anonymity:"Yes",leave:"Somewhat easy",mental_health_consequence:"No"},
  {age:26,gender:"Male",country:"India",self_employed:"No",family_history:"Yes",treatment:"Yes",work_interfere:"Sometimes",no_employees:"100-500",remote_work:"Yes",tech_company:"Yes",benefits:"Yes",care_options:"Yes",wellness_program:"No",seek_help:"Yes",anonymity:"Yes",leave:"Somewhat easy",mental_health_consequence:"No"},

  // ── Sweden ────────────────────────────────────────────────────────────────
  {age:30,gender:"Male",country:"Sweden",self_employed:"No",family_history:"No",treatment:"No",work_interfere:"Never",no_employees:"26-100",remote_work:"Yes",tech_company:"Yes",benefits:"Yes",care_options:"Yes",wellness_program:"Yes",seek_help:"Yes",anonymity:"Yes",leave:"Easy",mental_health_consequence:"No"},
  {age:35,gender:"Female",country:"Sweden",self_employed:"No",family_history:"Yes",treatment:"Yes",work_interfere:"Sometimes",no_employees:"100-500",remote_work:"No",tech_company:"Yes",benefits:"Yes",care_options:"Yes",wellness_program:"Yes",seek_help:"Yes",anonymity:"Yes",leave:"Easy",mental_health_consequence:"No"},
  {age:29,gender:"Male",country:"Sweden",self_employed:"No",family_history:"No",treatment:"No",work_interfere:"Rarely",no_employees:"More than 1000",remote_work:"No",tech_company:"Yes",benefits:"Yes",care_options:"Yes",wellness_program:"Yes",seek_help:"Yes",anonymity:"Yes",leave:"Easy",mental_health_consequence:"No"},

  // ── France ────────────────────────────────────────────────────────────────
  {age:32,gender:"Male",country:"France",self_employed:"No",family_history:"No",treatment:"No",work_interfere:"Sometimes",no_employees:"100-500",remote_work:"No",tech_company:"Yes",benefits:"Yes",care_options:"Yes",wellness_program:"No",seek_help:"Yes",anonymity:"Yes",leave:"Somewhat easy",mental_health_consequence:"No"},
  {age:27,gender:"Female",country:"France",self_employed:"No",family_history:"Yes",treatment:"Yes",work_interfere:"Often",no_employees:"26-100",remote_work:"Yes",tech_company:"Yes",benefits:"Yes",care_options:"Yes",wellness_program:"Yes",seek_help:"Yes",anonymity:"Yes",leave:"Easy",mental_health_consequence:"No"},
  {age:38,gender:"Male",country:"France",self_employed:"No",family_history:"No",treatment:"No",work_interfere:"Never",no_employees:"More than 1000",remote_work:"No",tech_company:"No",benefits:"Yes",care_options:"Yes",wellness_program:"Yes",seek_help:"Yes",anonymity:"Yes",leave:"Easy",mental_health_consequence:"No"},

  // ── New Zealand ───────────────────────────────────────────────────────────
  {age:34,gender:"Male",country:"New Zealand",self_employed:"No",family_history:"Yes",treatment:"Yes",work_interfere:"Sometimes",no_employees:"26-100",remote_work:"Yes",tech_company:"Yes",benefits:"Yes",care_options:"Yes",wellness_program:"No",seek_help:"Yes",anonymity:"Yes",leave:"Somewhat easy",mental_health_consequence:"No"},
  {age:29,gender:"Female",country:"New Zealand",self_employed:"No",family_history:"No",treatment:"No",work_interfere:"Rarely",no_employees:"6-25",remote_work:"No",tech_company:"Yes",benefits:"Yes",care_options:"Yes",wellness_program:"Yes",seek_help:"Yes",anonymity:"Yes",leave:"Easy",mental_health_consequence:"No"},
  {age:41,gender:"Male",country:"New Zealand",self_employed:"No",family_history:"No",treatment:"No",work_interfere:"Never",no_employees:"100-500",remote_work:"No",tech_company:"Yes",benefits:"Yes",care_options:"Yes",wellness_program:"Yes",seek_help:"Yes",anonymity:"Yes",leave:"Easy",mental_health_consequence:"No"},

  // ── Brazil ────────────────────────────────────────────────────────────────
  {age:26,gender:"Male",country:"Brazil",self_employed:"No",family_history:"No",treatment:"No",work_interfere:"Sometimes",no_employees:"More than 1000",remote_work:"No",tech_company:"Yes",benefits:"Yes",care_options:"Not sure",wellness_program:"No",seek_help:"Yes",anonymity:"Don't know",leave:"Somewhat easy",mental_health_consequence:"No"},
  {age:30,gender:"Female",country:"Brazil",self_employed:"No",family_history:"Yes",treatment:"Yes",work_interfere:"Often",no_employees:"100-500",remote_work:"No",tech_company:"Yes",benefits:"Yes",care_options:"Yes",wellness_program:"Yes",seek_help:"Yes",anonymity:"Yes",leave:"Easy",mental_health_consequence:"No"},

  // ── More US to ensure proper proportions ─────────────────────────────────
  {age:31,gender:"Male",country:"United States",self_employed:"No",family_history:"No",treatment:"No",work_interfere:"Rarely",no_employees:"26-100",remote_work:"No",tech_company:"Yes",benefits:"Yes",care_options:"Yes",wellness_program:"No",seek_help:"Yes",anonymity:"Yes",leave:"Somewhat easy",mental_health_consequence:"No"},
  {age:45,gender:"Female",country:"United States",self_employed:"No",family_history:"Yes",treatment:"Yes",work_interfere:"Often",no_employees:"More than 1000",remote_work:"No",tech_company:"Yes",benefits:"Yes",care_options:"Yes",wellness_program:"Yes",seek_help:"Yes",anonymity:"Yes",leave:"Easy",mental_health_consequence:"No"},
  {age:23,gender:"Male",country:"United States",self_employed:"No",family_history:"No",treatment:"No",work_interfere:"Never",no_employees:"6-25",remote_work:"No",tech_company:"Yes",benefits:"Don't know",care_options:"Not sure",wellness_program:"Don't know",seek_help:"Don't know",anonymity:"Don't know",leave:"Don't know",mental_health_consequence:"No"},
  {age:38,gender:"Male",country:"United States",self_employed:"No",family_history:"Yes",treatment:"Yes",work_interfere:"Sometimes",no_employees:"100-500",remote_work:"Yes",tech_company:"Yes",benefits:"Yes",care_options:"Yes",wellness_program:"Yes",seek_help:"Yes",anonymity:"Yes",leave:"Easy",mental_health_consequence:"No"},
  {age:29,gender:"Female",country:"United States",self_employed:"No",family_history:"No",treatment:"No",work_interfere:"Rarely",no_employees:"500-1000",remote_work:"No",tech_company:"Yes",benefits:"Yes",care_options:"Yes",wellness_program:"Yes",seek_help:"Yes",anonymity:"Yes",leave:"Easy",mental_health_consequence:"No"},
  {age:34,gender:"Other",country:"United States",self_employed:"No",family_history:"Yes",treatment:"Yes",work_interfere:"Often",no_employees:"26-100",remote_work:"No",tech_company:"Yes",benefits:"Yes",care_options:"Yes",wellness_program:"No",seek_help:"Yes",anonymity:"Yes",leave:"Somewhat easy",mental_health_consequence:"No"},
  {age:27,gender:"Male",country:"United States",self_employed:"Yes",family_history:"No",treatment:"No",work_interfere:"Sometimes",no_employees:"1-5",remote_work:"Yes",tech_company:"Yes",benefits:"No",care_options:"No",wellness_program:"No",seek_help:"No",anonymity:"Yes",leave:"Very difficult",mental_health_consequence:"No"},
  {age:42,gender:"Male",country:"United States",self_employed:"No",family_history:"No",treatment:"No",work_interfere:"Never",no_employees:"More than 1000",remote_work:"No",tech_company:"Yes",benefits:"Yes",care_options:"Yes",wellness_program:"Yes",seek_help:"Yes",anonymity:"Yes",leave:"Easy",mental_health_consequence:"No"},
  {age:26,gender:"Female",country:"United States",self_employed:"No",family_history:"Yes",treatment:"Yes",work_interfere:"Often",no_employees:"6-25",remote_work:"No",tech_company:"No",benefits:"No",care_options:"No",wellness_program:"No",seek_help:"No",anonymity:"No",leave:"Difficult",mental_health_consequence:"Yes"},
  {age:35,gender:"Male",country:"United States",self_employed:"No",family_history:"Yes",treatment:"Yes",work_interfere:"Sometimes",no_employees:"26-100",remote_work:"Yes",tech_company:"Yes",benefits:"Yes",care_options:"Yes",wellness_program:"Yes",seek_help:"Yes",anonymity:"Yes",leave:"Easy",mental_health_consequence:"No"},
  {age:30,gender:"Male",country:"United States",self_employed:"No",family_history:"No",treatment:"No",work_interfere:"Rarely",no_employees:"100-500",remote_work:"No",tech_company:"Yes",benefits:"Yes",care_options:"Yes",wellness_program:"No",seek_help:"Yes",anonymity:"Yes",leave:"Somewhat easy",mental_health_consequence:"No"},
  {age:48,gender:"Female",country:"United States",self_employed:"No",family_history:"Yes",treatment:"Yes",work_interfere:"Sometimes",no_employees:"500-1000",remote_work:"No",tech_company:"Yes",benefits:"Yes",care_options:"Yes",wellness_program:"Yes",seek_help:"Yes",anonymity:"Yes",leave:"Easy",mental_health_consequence:"No"},
  {age:22,gender:"Male",country:"United States",self_employed:"No",family_history:"No",treatment:"No",work_interfere:"Never",no_employees:"6-25",remote_work:"No",tech_company:"Yes",benefits:"Don't know",care_options:"Not sure",wellness_program:"Don't know",seek_help:"Don't know",anonymity:"Don't know",leave:"Don't know",mental_health_consequence:"No"},
  {age:36,gender:"Male",country:"United States",self_employed:"No",family_history:"Yes",treatment:"Yes",work_interfere:"Often",no_employees:"More than 1000",remote_work:"No",tech_company:"Yes",benefits:"Yes",care_options:"Yes",wellness_program:"Yes",seek_help:"Yes",anonymity:"Yes",leave:"Easy",mental_health_consequence:"No"},
  {age:25,gender:"Female",country:"United States",self_employed:"No",family_history:"No",treatment:"No",work_interfere:"Rarely",no_employees:"26-100",remote_work:"Yes",tech_company:"Yes",benefits:"Yes",care_options:"Yes",wellness_program:"Yes",seek_help:"Yes",anonymity:"Yes",leave:"Easy",mental_health_consequence:"No"},
  {age:40,gender:"Male",country:"United States",self_employed:"No",family_history:"Yes",treatment:"Yes",work_interfere:"Sometimes",no_employees:"100-500",remote_work:"No",tech_company:"Yes",benefits:"Yes",care_options:"Yes",wellness_program:"No",seek_help:"Yes",anonymity:"Yes",leave:"Somewhat easy",mental_health_consequence:"No"},
  {age:33,gender:"Other",country:"United States",self_employed:"No",family_history:"Yes",treatment:"Yes",work_interfere:"Often",no_employees:"26-100",remote_work:"No",tech_company:"Yes",benefits:"Yes",care_options:"Not sure",wellness_program:"Don't know",seek_help:"Yes",anonymity:"Don't know",leave:"Don't know",mental_health_consequence:"Maybe"},
  {age:28,gender:"Male",country:"United States",self_employed:"No",family_history:"No",treatment:"No",work_interfere:"Never",no_employees:"More than 1000",remote_work:"No",tech_company:"Yes",benefits:"Yes",care_options:"Yes",wellness_program:"Yes",seek_help:"Yes",anonymity:"Yes",leave:"Easy",mental_health_consequence:"No"},
];

/**
 * Company size sort order for consistent axis display.
 */
const COMPANY_SIZE_ORDER = ["1-5","6-25","26-100","100-500","500-1000","More than 1000"];

/**
 * Work-interference levels in logical order.
 */
const WORK_INTERFERE_ORDER = ["Never","Rarely","Sometimes","Often"];

/**
 * Pastel colour palette used consistently across all charts.
 */
const PALETTE = {
  blue:    "#a8c8f0",
  pink:    "#f5b8c8",
  mint:    "#a8dfc0",
  peach:   "#fdd9a8",
  lavender:"#c8b8e8",
  rose:    "#f0c0c0",
  sky:     "#b0daf5",
  sage:    "#c0d8b8",
  butter:  "#f8e8a8",
  lilac:   "#d8c0f0",
  treatment_yes: "#a8c8f0",
  treatment_no:  "#f5b8c8",
};
